name: ' '
appendCommitMessageToRunName: true

resources:
    repositories:
        - repository: devops
          type: github
          name: BiblioNexusStudio/devops
          endpoint: BiblioNexusStudio

pr: none
trigger:
    - master

pool:
    vmImage: ubuntu-latest

variables:
    - group: content-manager-web-dev
    - group: content-manager-web-qa
    - group: content-manager-web-prod
    - group: github-app

stages:
    - ${{ if contains(variables['Build.SourceVersionMessage'], '(#') }}:
          - stage: cleanup_qa_preview_env
            dependsOn: []
            jobs:
                - job: cleanup
                  steps:
                      - template: templates/checkout_master.yml@devops
                      - template: templates/setup_node.yml@devops
                      - task: AzureCLI@2
                        inputs:
                            azureSubscription: BiblioNexusAzureSubscription
                            scriptType: bash
                            scriptLocation: inlineScript
                            inlineScript: |
                                az staticwebapp environment delete \
                                    --yes --name content-manager-web-qa \
                                    --environment-name "pr$(echo $BUILD_SOURCEVERSIONMESSAGE | grep -oP '\(#\K\d+')"
                        displayName: Destroy preview environment in Azure
                      - checkout: devops
                        path: devops
                      - script: |
                            $(Pipeline.Workspace)/devops/github-cli/script.sh deployment \
                                --privateKeyBase64 "$GITHUB_APP_PRIVATE_KEY_BASE64" \
                                --environment "pr$(echo $BUILD_SOURCEVERSIONMESSAGE | grep -oP '\(#\K\d+')" \
                                --repo content-manager-web \
                                --destroy
                        env:
                            GITHUB_APP_PRIVATE_KEY_BASE64: $(GithubAppPrivateKeyBase64)
                        displayName: Destroy preview environment in GitHub

    - template: templates/setup_cache.yml

    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: dev
          DependsOn: [setup_cache]
          AzureDevopsEnvName: content-manager-web-dev
          CheckoutTemplate: templates/checkout_master.yml@devops
          DeployApiToken: $(AzureStaticWebAppsApiTokenDev)
          DeployUrl: $(AzureStaticWebAppsDeployUrlDev)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)
          SourceDirectory: content-manager-web

    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: qa
          DependsOn: [setup_cache]
          AzureDevopsEnvName: content-manager-web-qa
          CheckoutTemplate: templates/checkout_master.yml@devops
          DeployApiToken: $(AzureStaticWebAppsApiTokenQa)
          DeployUrl: $(AzureStaticWebAppsDeployUrlQa)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)
          SourceDirectory: content-manager-web

    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: prod
          DependsOn: [setup_cache]
          AzureDevopsEnvName: content-manager-web-prod
          CheckoutTemplate: templates/checkout_master.yml@devops
          CreateGithubRelease: true
          DeployApiToken: $(AzureStaticWebAppsApiTokenProd)
          DeployUrl: $(AzureStaticWebAppsDeployUrlProd)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)
          SourceDirectory: content-manager-web
