# make the name of the pipeline relevant and associated with the pull request
name: $[ format('PR {0} (build {1})', variables['System.PullRequest.PullRequestNumber'], counter(format('build{0}', variables['System.PullRequest.PullRequestNumber']), 1)) ]
appendCommitMessageToRunName: true

resources:
    repositories:
        - repository: devops
          type: github
          name: BiblioNexusStudio/devops
          endpoint: BiblioNexusStudio

trigger: none

pool:
    vmImage: ubuntu-latest

variables:
    - group: content-manager-web-dev
    - group: content-manager-web-qa
    - group: github-app

stages:
    - stage: build
      jobs:
          - job: lint_test
            steps:
                - template: templates/checkout_pr.yml@devops
                - template: templates/install_deps.yml
                - script: yarn build
                  displayName: Build
                - script: yarn lint:ci
                  displayName: ESLint
                - script: yarn test
                  displayName: Test

    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: dev
          DependsOn: [build]
          AzureDevopsEnvName: content-manager-web-dev
          CheckoutTemplate: templates/checkout_pr.yml@devops
          DeployApiToken: $(AzureStaticWebAppsApiTokenDev)
          DeployUrl: $(AzureStaticWebAppsDeployUrlDev)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)
          SourceDirectory: content-manager-web

    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: qa
          DependsOn: [build]
          AzureDevopsEnvName: content-manager-web-qa-preview
          CheckoutTemplate: templates/checkout_pr.yml@devops
          DeployApiToken: $(AzureStaticWebAppsApiTokenQa)
          DeployUrl: $(AzureStaticWebAppsDeployUrlQaPreview)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)
          SourceBranchForPreviewEnvironment: $(Build.SourceBranch)
          SourceDirectory: content-manager-web
