name: Build and deploy to env
description: Builds and deploys to a specific environment. Assumes the source code has already been checked out.

inputs:
    environment:
        description: Environment to deploy to
        required: true
    api-token:
        description: API token for deployment
        required: true
    override-output-url:
        description: Overrides the output deployed-url
        required: false
    linear-api-key:
        description: Linear API key
        required: false
    slack-bot-token:
        description: Slack bot token
        required: false
    github-token:
        description: GitHub token
        required: false

outputs:
    deployed-url:
        description: The URL of the newly deployed app
        value: ${{ steps.calculate-url.outputs.url }}

runs:
    using: composite
    steps:
        - name: Notify Slack deploy is starting
          id: slack-notify
          if: ${{ !contains(inputs.environment, 'dev') }}
          uses: BiblioNexusStudio/github-action-slack-notify-build@main
          with:
              channel_id: C05UPTGQGP9
              status: RUNNING
              color: warning
              environment: ${{ inputs.environment }}
              default_branch_name: master
              service_name: CMS
          env:
              SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
              GITHUB_TOKEN: ${{ inputs.github-token }}
              LINEAR_API_KEY: ${{ inputs.linear-api-key }}
        - name: Use Node.js
          uses: actions/setup-node@v4.0.3
          with:
              node-version: 22.11.0
              cache: yarn
        - name: Install dependencies
          run: yarn install --frozen-lockfile
          shell: bash
        - name: Setup ENV vars config
          run: yarn use-config ${{ inputs.environment }}
          shell: bash
        - name: Build
          run: yarn run build
          shell: bash
        - name: Setup Azure config
          run: cp staticwebapp.config.json build/
          shell: bash
        - name: Deploy to Azure WebApp
          id: deploy-to-webapp
          uses: azure/static-web-apps-deploy@v1
          with:
              azure_static_web_apps_api_token: ${{ inputs.api-token }}
              skip_app_build: true
              skip_api_build: true
              action: upload
              app_location: build
              output_location: ''
        - name: Notify Slack deploy status
          if: ${{ !cancelled() && !contains(inputs.environment, 'dev') }}
          uses: BiblioNexusStudio/github-action-slack-notify-build@main
          with:
              channel_id: C05UPTGQGP9
              status: ${{ github.action_status == 'failure' && 'FAILURE' || 'SUCCESS' }}
              color: ${{ github.action_status == 'failure' && 'danger' || 'good' }}
              environment: ${{ inputs.environment }}
              default_branch_name: master
              service_name: CMS
              message_id: ${{ steps.slack-notify.outputs.message_id }}
          env:
              SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
              GITHUB_TOKEN: ${{ inputs.github-token }}
              LINEAR_API_KEY: ${{ inputs.linear-api-key }}
        - name: Calculate URL
          id: calculate-url
          run: |
              if [[ -n "${{ inputs.override-output-url }}" ]]; then
                  echo "url=${{ inputs.override-output-url }}" >> $GITHUB_OUTPUT
              else
                  echo "url=${{ steps.deploy-to-webapp.outputs.static_web_app_url }}" >> $GITHUB_OUTPUT
              fi
          shell: bash
