# Creates a Hotfix PR using the BiblioNexusStudio/github-actions/create-hotfix action
# See https://github.com/BiblioNexusStudio/github-actions for docs

name: Create Hotfix

on:
    workflow_dispatch:
        inputs:
            commit_id:
                description: "Commit SHA from master you'd like to apply"
                required: true

permissions:
    contents: read
    deployments: read

jobs:
    create-hotfix:
        runs-on: ubuntu-latest
        steps:
            - uses: BiblioNexusStudio/github-actions/create-hotfix@master
              with:
                  prod_environment: prod
                  commit_id: ${{ github.event.inputs.commit_id }}
                  app_id: ${{ secrets.BIBLIONEXUS_BOT_APP_ID }}
                  private_key: ${{ secrets.BIBLIONEXUS_BOT_PRIVATE_KEY }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
