name: Post-merge

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    contents: write
    deployments: read
    pull-requests: read

jobs:
    deploy_to_dev:
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        name: Deploy to dev
        runs-on: ubuntu-latest
        environment:
            name: dev
            url: ${{ steps.deploy.outputs.deployed-url }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            - uses: ./.github/actions/build-and-deploy-to-env
              id: deploy
              with:
                  environment: dev
                  api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
                  html-diff-ts-deploy-key: ${{ secrets.HTML_DIFF_TS_DEPLOY_KEY }}
                  override-output-url: ${{ vars.URL_DEV }}

    deploy_to_qa:
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        name: Deploy to qa
        runs-on: ubuntu-latest
        environment:
            name: qa
            url: ${{ steps.deploy.outputs.deployed-url }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            - uses: ./.github/actions/build-and-deploy-to-env
              id: deploy
              with:
                  environment: qa
                  api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_QA }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  linear-api-key: ${{ secrets.LINEAR_API_KEY }}
                  slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
                  html-diff-ts-deploy-key: ${{ secrets.HTML_DIFF_TS_DEPLOY_KEY }}
                  override-output-url: ${{ vars.URL_QA }}

    deploy_to_prod:
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        name: Deploy to prod
        runs-on: ubuntu-latest
        environment:
            name: prod
            url: ${{ steps.deploy.outputs.deployed-url }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            - uses: ./.github/actions/build-and-deploy-to-env
              id: deploy
              with:
                  environment: prod
                  api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  linear-api-key: ${{ secrets.LINEAR_API_KEY }}
                  slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
                  html-diff-ts-deploy-key: ${{ secrets.HTML_DIFF_TS_DEPLOY_KEY }}
                  override-output-url: ${{ vars.URL_PROD }}
