# This workflow runs automatically on pushes to master.
# It can also be run manually via workflow_dispatch. It uses check-if-branch-should-deploy
# to prevent cluttering the deployments list with initial release-hotfix- branches.
#
# It builds for each environment individually and deploys in the same step:
# - Deploy to Dev
# - Deploy to QA
# - Deploy to Production
#
# Note: Environment deployments require approval through GitHub environment protection rules

name: Post-merge

on:
    push:
        branches:
            - master
            - 'release-hotfix-*'
    workflow_dispatch:

permissions:
    contents: write
    deployments: read
    pull-requests: read

jobs:
    check_should_deploy:
        runs-on: ubuntu-latest
        outputs:
            should_deploy: ${{ github.event_name == 'workflow_dispatch' || steps.check_deploy.outputs.should_deploy == 'true' }}
        steps:
            - id: check_deploy
              if: github.event_name != 'workflow_dispatch'
              uses: BiblioNexusStudio/github-actions/check-if-branch-should-deploy@master
              with:
                  current_branch: ${{ github.ref_name }}

    deploy_to_dev:
        needs:
            - check_should_deploy
        if: needs.check_should_deploy.outputs.should_deploy == 'true'
        name: Deploy to dev
        runs-on: ubuntu-latest
        environment:
            name: dev
            url: ${{ steps.deploy.outputs.deployed-url }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4.1.7
            - uses: ./.github/actions/build-and-deploy-to-env
              id: deploy
              with:
                  environment: dev
                  api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
                  override-output-url: ${{ vars.URL_DEV }}

    deploy_to_qa:
        needs:
            - check_should_deploy
        if: needs.check_should_deploy.outputs.should_deploy == 'true'
        name: Deploy to qa
        runs-on: ubuntu-latest
        environment:
            name: qa
            url: ${{ steps.deploy.outputs.deployed-url }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4.1.7
            - uses: ./.github/actions/build-and-deploy-to-env
              id: deploy
              with:
                  environment: qa
                  api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_QA }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  linear-api-key: ${{ secrets.LINEAR_API_KEY }}
                  slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
                  override-output-url: ${{ vars.URL_QA }}

    deploy_to_prod:
        needs:
            - check_should_deploy
        if: needs.check_should_deploy.outputs.should_deploy == 'true'
        name: Deploy to prod
        runs-on: ubuntu-latest
        environment:
            name: prod
            url: ${{ steps.deploy.outputs.deployed-url }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4.1.7
            - uses: ./.github/actions/build-and-deploy-to-env
              id: deploy
              with:
                  environment: prod
                  api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  linear-api-key: ${{ secrets.LINEAR_API_KEY }}
                  slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
                  override-output-url: ${{ vars.URL_PROD }}
            - uses: BiblioNexusStudio/github-actions/delete-hotfix-branch@master
              with:
                  current_branch: ${{ github.ref_name }}
                  app_id: ${{ secrets.BIBLIONEXUS_BOT_APP_ID }}
                  private_key: ${{ secrets.BIBLIONEXUS_BOT_PRIVATE_KEY }}
